apiVersion: apps/v1
kind: Deployment

metadata:
  name: cloud-native-devops
  namespace: devops-platform

spec:
  replicas: 2

  selector:
    matchLabels:
      app: cloud-native-devops

  template:
    metadata:
      labels:
        app: cloud-native-devops

    spec:
      containers:
        - name: cloud-native-devops
          image: cloud-native-devops:v3
          imagePullPolicy: Never

          envFrom:
            - configMapRef:
                name: app-config

          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"